### ISSUE TITLE
These credentials do not match our records.

### ISSUE THREAD

**Issue by fey** [bpocallaghan/titan-starter#16]
Tried to login with creds
User: github@bpocallaghan.co.za
Password: github
https://titan.bpocallaghan.co.za/auth/login
Get error

**Comment by bpocallaghan** [comment]
@fey 
Oopsie, sorry about that. 
Please try again.

Sorry, things a bit crazy and forgot to update the users :)
Thanks for looking into the repository - please give me a shout if you have any questions / issues...

**Comment by fey** [comment]
Thanks, it works
