### ISSUE TITLE
Trouble with auth.blade.php css

### ISSUE THREAD

**Issue by sidor1989** [bpocallaghan/titan-starter#17]
Good day @bpocallaghan !

I start explore your solution! It's great! 

And i get troble with CSS

https://github.com/bpocallaghan/titan-starter/blob/9bcffba71be5a860d2766de8cca25348499ec1f5/resources/views/auth/auth.blade.php#L14

But in 
https://github.com/bpocallaghan/titan-starter/blob/master/webpack.mix.js
I don't see app.css.
Where I can find him?

**Comment by bpocallaghan** [comment]
@sidor1989 
Hi Sidor, thank you for looking at the repository. 

Whoopsie, that is my mistake, I recently renamed the app.css to website.css. Please change that to website.css. Sorry, Recently made some big changes / updates to it again. Try to work on it as much as I can :)

Please let me know if you have any more issues / feedback.

**Comment by bpocallaghan** [comment]
Hi @sidor1989 

Sorry, I lied - please change to admin.css

https://github.com/bpocallaghan/titan-starter/blob/master/resources/views/auth/auth.blade.php#L14

It seems when I renamed it - the styles comes from admin.css
The login page definitely needs a style upgrade :)

**Comment by sidor1989** [comment]
Great! It's solved! 

Thank you so much @bpocallaghan.

**Comment by bpocallaghan** [comment]
@sidor1989 
Awesome - please shout if u have any more issues / questions / feedback.
