### ISSUE TITLE
Great job! But nothing for models translation?

### ISSUE THREAD

**Issue by alessandromarotta** [bpocallaghan/titan-starter#19]
Titan is really amazing but I didn't found anything for models translation. What package do you suggest to integrate in Titan?

Thank you

**Comment by bpocallaghan** [comment]
Hi @alessandromarotta 
Thank you for the kind words.
Yes, unfortunately you can not use multi languages yet (one thing that is on my list but way future)

I would suggest looking at [Spatie Translatable](https://github.com/spatie/laravel-translatable).
I have not used it but I usually see if spatie have a package similar before looking somewhere else.

Feel free to contribute any updates or the translatable update :)

Shout if you have any questions or suggestions.
