### ISSUE TITLE
Error!!!

### ISSUE THREAD

**Issue by 34534206** [bpocallaghan/titan-starter#20]
I got this page when i try to open after installation. Am i missing something??
![error](https://user-images.githubusercontent.com/66189342/87403847-193b9180-c5dd-11ea-82b5-d27dd555a3e7.png)

**Comment by bpocallaghan** [comment]
Hi @34534206 
Did you run the `php artisan db:seed` command
 - on local that error display, where it will display a 40 on production (if the pages table is empty)

**Comment by bpocallaghan** [comment]
Also note
The main differences between this project and the other one is.
 - more 'up to date' setup / theme / files, etc
 - tests
 - all the files are inside your app - no more hidden in the package, meaning you have 100% control.
 - unfortunately the other one does have more features (blog, newsletter, etc) as this one is kinda in development (or rather, I add stuff as I need them for projects)

**Comment by 34534206** [comment]
Thanks for your reply!  I got this when i run php artisan db:seed

![error](https://user-images.githubusercontent.com/66189342/87410396-f9f53200-c5e5-11ea-9dab-b30d7557c668.png)

**Comment by bpocallaghan** [comment]
Hi @34534206 
Mmmm, sorry about that - you are having a hard time with this - did not install a new project recently :)

Please have a look at the latest commit for a fix (it is the csv - empty string/null that needed a bit of love)

Just download latest file or copy those 2 lines I changed to get it working :)
[Commit / BasicSeeder.php](https://github.com/bpocallaghan/titan-starter/commit/73cc99c96388d456b272f9a98b0d5dc70d3d555c)

**Comment by 34534206** [comment]
Anyway Thanks! 
Sorry to put you in trouble. I tried again but don't know why it is still not working.
it shows Error
Call to a member function getParentsAndYou() on null

**Comment by bpocallaghan** [comment]
@34534206 
Howdy - no worries - I am here to help :)

Just want to confirm - the pages table did seed?
Can you just confirm your app_url in the .env file - if its the same as the one in browser.
That error means its not finding the page (no slug is matching)

If the above did not solve it - can then dd($slug) to see what is is and see if its in the pages table?
But please shout if its not working or I can help with something
