### ISSUE TITLE
no themplate

### ISSUE THREAD

**Issue by visionto** [bpocallaghan/titan-starter#23]
hi i have install titan but i do not have the themplate files for home and admin ??

**Comment by nadja97** [comment]
Hi @visionto 
Could you possibly elaborate on the issue at hand? 
This package does not have an install command, perhaps you were referring to one of our older packages - [titan](https://github.com/bpocallaghan/titan)?

**Comment by visionto** [comment]
Hi,

I have Setup (Basic) done 
But than i have no home css and admin css

**Comment by nadja97** [comment]
@visionto 
Did you run `npm install` and then `npm run prod` / `npm run dev`?

**Comment by visionto** [comment]
Okay i will try that

**Comment by visionto** [comment]
yes thanks it works great

**Comment by nadja97** [comment]
@visionto 
awesome - please shout if u have any more issues / questions / feedback, and thank you for using Titan Starter.
