### ISSUE TITLE
Image Doesn't Display!

### ISSUE THREAD

**Issue by maylmeto** [bpocallaghan/titan-starter#24]
Thank you for your amazing work!

Got problem working with images, as you can see in below screenshots, images are not showing in the page.

I wonder what would be the problem? 

![titan1](https://user-images.githubusercontent.com/44185259/89631892-1cb2f780-d8c1-11ea-8ae2-fcd0456fc8a1.png)
![titan](https://user-images.githubusercontent.com/44185259/89631985-3eac7a00-d8c1-11ea-8a1c-e0c3236c351e.png)

**Comment by bpocallaghan** [comment]
Hi @maylmeto 
Thanks for the compliment and giving this project a try.
Can you perhaps just double check / send me the path to the images? What I am after: Did the images successfully uploaded to /public/uploads/images/xxxx.png and what is the src tag in those images on that page?

**Comment by maylmeto** [comment]
Just checked, images did upload to the path as you mentioned but still images are not showing in the page.  

![path](https://user-images.githubusercontent.com/44185259/89641569-a8cd1b00-d8d1-11ea-8fb6-74776c2e9e11.png)

![path1](https://user-images.githubusercontent.com/44185259/89641586-b4b8dd00-d8d1-11ea-832a-66fbafd8255f.png)

**Comment by bpocallaghan** [comment]
@maylmeto 
Can you confirm the `APP_URL` in the `.env` file? I see the path is `http://localhost` ? Might it be that its missing the port or perhaps you have a shorter url like `http://site.test`. You can also try to have the src be `src=/uploads/images/{{ xxxx }}` If that makes sense ? I think the helper file for it is `{{ $news->cover_photo->thumb_url }}` or what do u have now?

**Comment by maylmeto** [comment]
Yes, i am using xampp localhost server, titan.test.

Also, i tried using src=/uploads/images/{{....}}, unfortunately it is also not working.

you can check screenshots below:

**show.blade.php**
![news_show](https://user-images.githubusercontent.com/44185259/89699845-bc1bcd00-d949-11ea-9ef3-100ed11d9f9c.png)

**source page of news** 
![news_sourcepage](https://user-images.githubusercontent.com/44185259/89699863-da81c880-d949-11ea-80be-d869590d7650.png)

**helper file**
![helper](https://user-images.githubusercontent.com/44185259/89699874-f2594c80-d949-11ea-9e6a-4d1a22a7ab0f.png)

**edited show.blade.php**
![after_edit_show](https://user-images.githubusercontent.com/44185259/89699931-5c71f180-d94a-11ea-8e72-00687b417867.png)

**Comment by maylmeto** [comment]
Thank you for your help!

Yes, as you said, i had problem with image path. Now, it is fixed.

**Comment by bpocallaghan** [comment]
@maylmeto 
Awesome, happy its working!
Please shout if u have any questions or issues. Have fun
