### ISSUE TITLE
Checkout Error In Products!

### ISSUE THREAD

**Issue by maylmeto** [bpocallaghan/titan-starter#25]
I wonder whether payment process system have been implemented or not? it gave me error.

It would be really nice if you could integrate payment system too if it hasn't one.

![product](https://user-images.githubusercontent.com/44185259/89726461-94f0f880-da3a-11ea-8bca-44b64bed8be4.png)

When i clicked the checkout button to complete payment process, i got screenshot as below : 

![transaction](https://user-images.githubusercontent.com/44185259/89726457-873b7300-da3a-11ea-92cc-850eeb6cbfb4.png)

**Comment by bpocallaghan** [comment]
@maylmeto 
Thanks for the suggestion, unfortunately the website's part is very basic, more like an example to give you a good head start to customize it for your liking. There is also no payment provider. There are a lot of resources on how to implement Stripe, if its supported in your country?

**Comment by maylmeto** [comment]
Okay. I will start implementing payment process system in my project soon.

Thanks for your amazing scripts! Cheers!

**Comment by bpocallaghan** [comment]
@maylmeto 
Awesome, no problem, glad you are happy. Can always do a PR if you like to add something ;)
Happy coding!
