### ISSUE TITLE
preview dead

### ISSUE THREAD

**Issue by LordRampantHump** [bpocallaghan/titan-starter#5]
preview dead

**Comment by bpocallaghan** [comment]
Hi @LordRampantHump 
Thanks - will have a look at it and let you know.

**Comment by bpocallaghan** [comment]
Hi @LordRampantHump 
Sorry for the trouble.

Please have another go at it.
We did a lot of big changes lately and have not yet updated all the documentation, etc yet.

Please also use the [latest version here](https://github.com/bpocallaghan/titan-starter-website)

Please let me know if you have any issues / comments. Thanks

**Comment by LordRampantHump** [comment]
looks like you have been busy! The demo site does not really demonstrate  much at the moment other than the admin lte section. Would be nice to see the store functionality and maybe a subscription method (recurring) in there. 
"Social Login" and "2fa" are a must also. 
Does it use UUID? 

If you capitalize any route it breaks:
https://titan.bpocallaghan.co.za/products
AS
https://titan.bpocallaghan.co.za/Products


Looks like its heading in a the right direction for sure!

**Comment by bpocallaghan** [comment]
Hi @LordRampantHump 
Demo - yeah sorry, been doing so many changes/updates lately that the website/front end is very minimal and mostly focused on the admin side of things. Feel free to add entries to see what happens.
Honestly the website/frontend will kinda stay minimal for a while as usually you have different themes and then the work is a bit irrelevant. But please let me know or can even contribute if you like ;)

Thanks - yeah - that is something new added recently :)
